<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <UserSecretsId>aspnet-DDT_Host-a077d2f4-d71b-4918-bf26-a74c1cb9a3c4</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DDT.Server\DDT.Server.csproj" />
    <ProjectReference Include="..\DDT.ServiceDefaults\DDT.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
