<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DDT.Pxe\DDT.Pxe.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\DDT.Protocols.Tests\Fixtures\**\*.bin" LinkBase="Fixtures" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
